### ISSUE TITLE
Unable to install Windows

### ISSUE THREAD

**Issue by jacobd082** [Botspot/wor-flasher#101]
Hello, I'm using a Raspberry Pi 4 Model B with a SanDisk Ultra PLUS 32 GB SD card. I first downloaded wor-flasher on Sep 30th on Raspberry Pi OS, via the command line. 

I have been unable to install Windows 10 & 11 with wor-flasher. The Raspberry Pi that I am using has been able to run Windows 11 in the past, on the same SD card and using wor-flasher. I am able to do the setup process in the README until it is time to boot the SD card. Upon doing so, it will act as normal, until it starts installing Windows, where at about 94%, it will show an error message, claiming that something has gone wrong. I have redone the process multiple times, and it always will show this error. Below is the log of the error.
![IMG_2521](https://user-images.githubusercontent.com/89097881/193423062-208f5048-5bb0-4aa0-a949-81a4607fd4d5.jpeg)

**Comment by Botspot** [comment]
this error seems to becaused by slow SD cards.

There are no known solutions other than to get a faster SD card.
See: https://github.com/Botspot/wor-flasher/issues/40
