### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by H46K3RL0L** [Botspot/wor-flasher#102]
## Setup:

- Windows 11
- Raspberry Pi 4 8GB
-XLRB Gaming 256GB
-September 30th
-Raspbian
## Procedure:
All I did was download it, run it, select the os and pi model, select en-us, select my storage drive, and it starts, a few minutes later, there is a prompt asking me what used to login is as (auto selected pi), my password, and to choose whether to shutdown or log in, log in does not work, neither does shutdown.

**Comment by Botspot** [comment]
It does not sound like your Pi booted to the Windows environment.

First, try starting over with fresh Raspbian 11 Bullseye, and then re-flash Windows as well. Then once the image has flashed, please shut down Raspbian, and remove all othe rstorage devices OTHER than the Windows one. And see if that boots.
