### ISSUE TITLE
Stuck on the black screen with big rpi-logo and a endless running circle

### ISSUE THREAD

**Issue by pengbins** [Botspot/wor-flasher#105]
## Setup:

- Which version of Windows you chose

 Selected Windows version: Windows 11 build 22621.755

- Raspberry Pi model

RPI_MODEL: 4

- Name of SD card you tried to flash (some are too slow or too small)

sumsung ssd 850 evo (250G)  + sataToUSB3 cabel

- What day you first downloaded wor-flasher

2022-Nov-04

- What linux operating system you are using to run wor-flasher on. (Raspberry Pi OS, Twister OS, Debian, etc)

Ubuntu 20.04.5 LTS  amd64

## Procedure:
1. run ./install-wor.sh    with no error info
2. unplug ssd from wor-flasher machine, plug to rpi4b, and boot rpi4b
3.  Stuck on the black screen with big rpi-logo and a endless running circle

After switch uefipackage back to v1.28 / v1.29, will continue to load 3 drivers and then report no installation disk was found, and also mouse and keyboard stop working.

**Comment by pengbins** [comment]
But wor.exe on Windows works.

**Comment by Botspot** [comment]
Did you get it resolved, @pengbins?

**Comment by pengbins** [comment]
> Did you get it resolved, @pengbins?

Not with `wor-flasher` on Ubuntu, but with `wor.exe` on Windows works. So I didn't try newer versions anymore.
