### ISSUE TITLE
Can't install Windows in Raspberry Pi Compute Model 4

### ISSUE THREAD

**Issue by Danielization** [Botspot/wor-flasher#106]
Hi, I have successfully downloaded WoR-flasher, run WoR-flasher using the graphical interface and flash windows to USB storage. When I restart my CM4 and boot up, at first it shows Raspberry Pi logo, but when it starts to extracting Windows, it shows error and restart itself.  It keeps on repeating the same progress for more than an hour and like an endless loop.

I read an article online and said it has no problem install in CM3, therefore isn't WOR can't install in CM4 yet?

**Comment by Botspot** [comment]
I think CM4 never worked.
