### ISSUE TITLE
Wor flasher not booting

### ISSUE THREAD

**Issue by dogehy** [Botspot/wor-flasher#108]
Whenever I boot it, i just get a picture of the raspberry and then two messages that say error: could not detect network connection. i could go into bios settings, but I don't know what to do there

**Comment by dogehy** [comment]
![image](https://user-images.githubusercontent.com/121187427/208970705-672c2658-7893-4a89-afbd-9c29ba5ca397.jpg)

**Comment by Botspot** [comment]
Turn off your pi, and then turn it on again. This time please don't press any keys and in 30 minutes or so it should reach a purple screen that will begin the installation process.
Lack of a network will display a warning on this screen, but it should not prevent the system from reaching the installation screen. I think you just need to give it more time.

**Comment by dogehy** [comment]
thanks so much for replying. however, 3 hours later and nothing has happened. is there a problem with the version of windows i'm using? are there any known problems with windows 10?![Uploading 209002583...]![image](https://user-images.githubusercontent.com/121187427/209002597-b7cc12d5-511f-4832-b1cd-42446ea28e4d.jpeg)

**Comment by Botspot** [comment]
Are you using a Pi3 or a Pi4?
What is the brand and model of your sd card?

**Comment by dogehy** [comment]
pi four 4gb, pny 64gb card

**Comment by Botspot** [comment]
> pi four 4gb, pny 64gb card

What is the speed rating on that sd card? A1? Class 10?
Do you have any other SD cards or usb drives that you can try?
