### ISSUE TITLE
Wifi

### ISSUE THREAD

**Issue by dogehy** [Botspot/wor-flasher#110]
## Setup:

- Which version of Windows you chose
- Raspberry Pi model
- Name of SD card you tried to flash (some are too slow or too small)
- What day you first downloaded wor-flasher
- What linux operating system you are using to run wor-flasher on. (Raspberry Pi OS, Twister OS, Debian, etc)

## Procedure:
Tell us what you did, step by step. Be specific enough so that one of us would be able to replicate your setup.
![IMG_20230109_075343](https://user-images.githubusercontent.com/121187427/211350680-806c9e40-72f6-481d-85cd-39c7f1225ac4.jpg)

When I try to use windows 10, the wifi won't work. I have a TP-Link adapter if that has any use. Is there any known fixes?

**Comment by Botspot** [comment]
See the readme.
![2023-01-09-160615_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/211418275-1ee96ac9-66a5-4d28-bd77-3e7586d5f0d2.png)

**Comment by Botspot** [comment]
There is one working driver for a particular wifi usb dongle. I don't know the details of it. You can consult https://worproject.com - I think the info is available somewhere - maybe in their discord.

**Comment by Botspot** [comment]
Ethernet works though.
