### ISSUE TITLE
Wifi icon not show on windows 11

### ISSUE THREAD

**Issue by asrafnasri** [Botspot/wor-flasher#111]
## Setup:

- Which version of Windows you chose (windows 11 pro)
- Raspberry Pi model (4b 8gb)
- Name of SD card you tried to flash (some are too slow or too small) m.2 ssd 150gb samsung
- What day you first downloaded wor-flasher (january 2023)
- What linux operating system you are using to run wor-flasher on. (Raspberry Pi OS)

## Procedure:
Tell us what you did, step by step. Be specific enough so that one of us would be able to replicate your setup.

When windows has installed wifi icon not shown and no wifi settings in windows setting, i didn't try do anything yet

**Comment by Itai-Nelken** [comment]
As far as I know there are no drivers for the onboard rpi wifi chip. 
The ethernet port works and you can use hotspot over bluetooth as well I think.

**Comment by Botspot** [comment]
@Itai-Nelken is correct.

Please refer to the main information found at https://github.com/Botspot/wor-flasher.
![2023-01-09-160615_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/211418275-1ee96ac9-66a5-4d28-bd77-3e7586d5f0d2.png)
