### ISSUE TITLE
Unable to download https://worproject.com/dldserv/esd/getversions.php

### ISSUE THREAD

**Issue by jvolker** [Botspot/wor-flasher#124]
## Setup:

- Which version of Windows you chose: 11
- Raspberry Pi model: 4
- What day you first downloaded wor-flasher: today
- What linux operating system you are using to run wor-flasher on. Raspberry Pi OS

## Procedure:
1. After selecting the Windows version (happens for Windows 10 and 11), I'm getting this error: `An error has occurred: Unable to download https://worproject.com/dldserv/esd/getversions.php Exiting now.` this comes up twice
2. then I can select more option to select language and flash drive
3. after clicking flash in the overview a terminal window opens prompting to choose a windows version
4. after choosing the windows version the same error comes back

**Comment by Botspot** [comment]
Either the site was down when you tried it, or your internet setup is blocking worproject.com.

Could you try going to https://worproject.com/dldserv/esd/getversions.php in a web browser?
