### ISSUE TITLE
wor sd card not booting up

### ISSUE THREAD

**Issue by mindmothership** [Botspot/wor-flasher#126]
## Setup:

- Which version of Windows you chose
windows 11
- Raspberry Pi model
rp4b 4gb
- Name of SD card you tried to flash (some are too slow or too small)
sandisk 128gb extreme pro
- What day you first downloaded wor-flasher
15th May 2023
- What linux operating system you are using to run wor-flasher on. (Raspberry Pi OS, Twister OS, Debian, etc)
ubuntu 22.04 lts

## Procedure:
Tell us what you did, step by step. Be specific enough so that one of us would be able to replicate your setup.

using ubuntu 22.04 
1) open up an external hard disk(this is hooked to rp4) that is fat32/ntfs to be used for used as working directory, near to 100gb hdd
2) on the explorer, right click to open a terminal
3) path to this hdd appears
4) git clone https://github.com/Botspot/wor-flasher
5) wor-flasher downloaded to the external hdd
6) go back to the terminal and type "~/wor-flasher/install-wor-gui.sh
7) a gui appears, choose windows 11 and pi4/400
8) choose english language
9) choose the device to flash ( a 128gb sandisk extreme pro micro sd card)
10) click on advanced... button to change working directory to the external hdd
11) dialog refresh with new pathing to the external hdd
12) press ok and Flash
13) wait

14) shut down rp4
15) take out both micro sd card (rp4 and usb connected micro sd card) and put the 128gb card into rp4 and power on.
16) rp4 boot up as if the card is not there

check1
1) with original rp4 micro sd card in rp4, boot up and go to DISK
2) insert the 128gb micro sd card
3) partition not shown with any text "bootable", only fat32 and ext4

check2
1) check content of 128gb micro sd card
2) card appears as two drives, 1 with multiple folders and files, another is install.wim if i am not wrong

**Comment by itsmurugappan** [comment]
this fixed for https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#updating-the-bootloader
