### ISSUE TITLE
"pnp driver watchdog" error on boot

### ISSUE THREAD

**Issue by TheHeroCraft1579** [Botspot/wor-flasher#13]
I installed Windows 11 on my 230GB M2 SSD but whenever i boot it takes around 10 Minutes and i get a windows error message saying "driver pnp watchdog". For installation i used the command line tool but didn't change any config. Im using a Pi 4 with 8 GB Ram

![IMG_20210903_225607](https://user-images.githubusercontent.com/38401902/132064613-07140a18-2441-4b9f-8fb4-b76ba79f009b.jpg)

Btw: I've used this SSD a lot and it worked perfectly fine with the Pi.

**Comment by mobilegmYT** [comment]
I'll redirect you to the WoR Discord server for support: https://discord.gg/worofficial

**Comment by Botspot** [comment]
I asked a WoR developer about this. He could only think of two causes for this error:

- Too high overclocking.
- Low voltage

**Comment by TheHeroCraft1579** [comment]
I haven't overclocked the Pi and im using the official Power Supply that came with the Pi

**Comment by TheHeroCraft1579** [comment]
I think its a power issue with my SSD because if i plug it in the USB port sometimes my keyboard doesn't respond (on another os) .

I also flashed it on my 32Gb SD Card but it always trys to boot over PXE. I also tried forcing it to boot fron SD from the setup but it just stays at the boot logo

**Comment by TheHeroCraft1579** [comment]
@
![Uploading IMG_20210904_150558.jpg…]()

**Comment by TheHeroCraft1579** [comment]
Here are some screenshots showing the contents of my SD Card

![2021-09-04_15-16](https://user-images.githubusercontent.com/38401902/132095784-d90ba5d5-450b-42e0-8214-6dcacd841e20.png)
![2021-09-04_15-17](https://user-images.githubusercontent.com/38401902/132095785-acf35fed-7775-4acb-8b57-50799e0f1632.png)
![2021-09-04_15-18](https://user-images.githubusercontent.com/38401902/132095786-ddd67379-1dac-4cd8-8025-9f90527bc07b.png)

**Comment by Itai-Nelken** [comment]
If your ssd is connected to a USB 3 port, try a usb 2 port. If I remember correctly fast usb drives are too mucj for the usb driver. Also try powering it externaly, maybe it uses too much power?

**Comment by Botspot** [comment]
> Here are some screenshots showing the contents of my SD Card
> 
> ![2021-09-04_15-17](https://user-images.githubusercontent.com/38401902/132095785-acf35fed-7775-4acb-8b57-50799e0f1632.png)
> ![2021-09-04_15-18](https://user-images.githubusercontent.com/38401902/132095786-ddd67379-1dac-4cd8-8025-9f90527bc07b.png)

Thank you for the screenshots. There ought to be three partitions there, and `install.wim` should have been extracted. Looks like the purple-screen installer did not finish up all the way. On first boot, did you see the purple screen with the white window in the center? 

> I think its a power issue with my SSD because if i plug it in the USB port sometimes my keyboard doesn't respond (on another os).

That could definitely be what's causing this. I used to have the same issue on Linux (SSD disconnecting) until I jerry-rigged the USB ports so the Pi's USB ports would never shut off due to over-current.

**Comment by TheHeroCraft1579** [comment]
No i didn't see a purple screen.

Here's a video:
https://streamable.com/jo74nv

**Comment by Botspot** [comment]
> Here's a video:
> https://streamable.com/jo74nv

Try re-flashing Windows to the SSD.

**Comment by TheHeroCraft1579** [comment]
The problem is i dont have a power cable for my ssd.

Also on sdcard no success. I tried to boot manually by selecting the bootloader (efi->boot->bootaa64.efi i guess?) 
This was the result: 
![IMG_20210906_132300](https://user-images.githubusercontent.com/38401902/132210350-081cba3a-c527-4d0d-bf6f-420065509123.jpg)

**Comment by TheHeroCraft1579** [comment]
I will now compare the ssd with my sdcard and see if there are different partitions, files,....

**Comment by TheHeroCraft1579** [comment]
I was just impatient with the SD Card it worked after 30 Minutes👍
