### ISSUE TITLE
not installed

### ISSUE THREAD

**Issue by Ivomir1** [Botspot/wor-flasher#131]
PLS can you help me with wor-flasher? I install on raspbian and started. Flashed my USB SSD drive with windows 11. Every works fine. Windows downloaded, flashed. Now i have this window. When i press shutdown my raspberry 4 turned off and nothing else. Windows 11 has not installed. When i press ON my raspberry turned on in old raspbian system.

![1](https://github.com/Botspot/wor-flasher/assets/116030560/578bd56e-4714-4bbb-922a-2655ce935ad9)

**Comment by Botspot** [comment]
You need to make your Pi boot from the USB SSD. In your case, it sounds like you just need to remove your sd card to force the Pi to boot from the SSD instead of the SD card.

**Comment by Botspot** [comment]
Any updates, @Ivomir1?
