### ISSUE TITLE
The image was downloaded successfully but it appears to be corrupted please run this script again

### ISSUE THREAD

**Issue by nasyx-rakeeb** [Botspot/wor-flasher#132]
- Which version of Windows you chose --> **11**
- Raspberry Pi model --> **Raspberry pi 4 B 8 GB**
- Name of SD card you tried to flash --> **Used an flash drive from san disk**
- What day you first downloaded wor-flasher --> **Today**
- What linux operating system you are using to run wor-flasher on --> **Raspberry pi OS 64 bit**

## Procedure:

I today tried to install `windows 11` first time on a flash drive of capacity `32 gb` which comes from **san disk** i cloned the wor flasher github repo and ran the gui script but after it installed the image and tried to verify it it showed me this error:

`The image was downloaded successfully but it appears to be corrupted please run this script again`

I tried to download again and same issue happend i tried with both `use ram` and `use home/wor-flasher` options but issue didnt go away i also tried the `pi apps` versionj of wor flasher but same issue with that one also. Then i edited the `install-wor.sh` file and modified the code where it verifies the image by matching the hashes then the issue got away but then it throwed another error it wasnt able to extract the image due to invalid compressed data it throwed error at `16%` i also looked online and only found this issue on raspberry pi forums where only one person had this issue once, after reading that forum discusson that person mentioned at last that he was unable to solve the issue as he is facing this from previous month and has skipped the installion of windows 11 through wor flasher now. Any help would be appericiated on this issue.

**Comment by Botspot** [comment]
I think the actual error message you saw was:
`Successfully downloaded ESD image, but it appears to be corrupted. Please run this script again.`

Did you see any errors when downloading?
Also, I would like to try to reproduce this, but the image I download depends on the language you chose. Since that could still be inaccurate, could you run wor-flasher again and take note of the `Input configuration:` lines of output? Specifically, I need you to send the BID line. The line looks like this: `BID: XXXXXXXX`

**Comment by nasyx-rakeeb** [comment]
Tha ks for the reply, I choose `en-us`, sure i will try to run it once again and copy paste the `IO` here, but there really isn't that much output in terminal because it fails very quickly after i click flash i guess just the 10 lines, in these lines it shows the config.txt and the error message

**Comment by nasyx-rakeeb** [comment]
So i ran it agan and here is what the output looks like afdter it throws the error:

`Checking for internet connection... Done

Input configuration:
DL_DIR: /home/nasyx/wor-flasher-files
RUN_MODE: gui
RPI_MODEL: 4
DEVICE: /dev/sda
CAN_INSTALL_ON_SAME_DRIVE: 1
BID: 22621.1702
WIN_LANG: en-us
CONFIG_TXT: ⤵
  > # don't change anything below this point #
  > arm_64bit=1
  > arm_boost=1
  > enable_uart=1
  > uart_2ndstage=1
  > enable_gic=1
  > armstub=RPI_EFI.fd
  > disable_commandline_tags=1
  > disable_overscan=1
  > device_tree_address=0x1f0000
  > device_tree_end=0x200000
  > dtoverlay=miniuart-bt
  > dtoverlay=upstream-pi4
CONFIG_TXT: ⤴
DRY_RUN: 0

Not downloading /home/nasyx/wor-flasher-files/peinstaller - folder exists
Not downloading /home/nasyx/wor-flasher-files/driverpackage - folder exists
Not downloading /home/nasyx/wor-flasher-files/pi4-uefipackage - folder exists
Downloading Windows ESD image
Done —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
Verifying download... 
Successfully downloaded ESD image, but it appears to be corrupted. Please run this script again.


`

I also attached the screenshot below

![SCREENSHOT](https://github.com/Botspot/wor-flasher/assets/89723867/024834a5-6c9f-4693-bf86-325937ca2083)

**Comment by Botspot** [comment]
I have tried to replicate your situation as much as possible, but I was not able to get this error to occur.
```
Input configuration:
DL_DIR: /home/pi/wor-flasher-files
RUN_MODE: gui
RPI_MODEL: 4
DEVICE: /dev/sdb
CAN_INSTALL_ON_SAME_DRIVE: 0
BID: 22621.1702
WIN_LANG: en-us
CONFIG_TXT: ⤵
  > # don't change anything below this point #
  > arm_64bit=1
  > arm_boost=1
  > enable_uart=1
  > uart_2ndstage=1
  > enable_gic=1
  > armstub=RPI_EFI.fd
  > disable_commandline_tags=1
  > disable_overscan=1
  > device_tree_address=0x1f0000
  > device_tree_end=0x200000
  > dtoverlay=miniuart-bt
  > dtoverlay=upstream-pi4
CONFIG_TXT: ⤴
DRY_RUN: 1

Downloading WoR PE-based installer from Google Drive
Done ———————————————————————————————————————————————————————————————————————————

Downloading ARM64 drivers
Done ———————————————————————————————————————————————————————————————————————————

Downloading Pi4 UEFI firmware
Done ———————————————————————————————————————————————————————————————————————————

Downloading Windows ESD image
Done ———————————————————————————————————————————————————————————————————————————
Verifying download... Done
```
Is your internet connection unreliable or slow? Are you using WiFi or Ethernet?

**Comment by nasyx-rakeeb** [comment]
I use WIFI, i tried it sgsin snd again and it is throwing me same wrror all the time, could it be because i am using cloudflare DNS in my raspberry pi os, because without cloudflare dns i can't access GitHub
`https://raw.githubusercontent.com` and some other sites i get timeout error, today i also tried to flash windows in usb drive by WOR flasher for windows 11, i downloaded the file from and ran the script on windows and it started downloading esd images and drivers and some other files, then after the download was finished it started converting it to ISO image, and it did convert it successfully, the size was around 4.5 GB, i had selected onoy Windows 11 Home on the download page, so when i tried to flash it and showed mounting image and then unmounting image, and then throwed this error, The image you selected is invalid, please select a valid arm64 build of version 1914 or newer,

**Comment by nasyx-rakeeb** [comment]
On which OS did you try to replicate the issue, if its raspberry pi os, is it 32 bit or 64 bit

**Comment by Botspot** [comment]
> On which OS did you try to replicate the issue, if its raspberry pi os, is it 32 bit or 64 bit

PiOS 64-bit

**Comment by nasyx-rakeeb** [comment]
I also tried on the same `Pi Os 64 bit` but all in vsin, i am currently trying with parrot os, it's downloading esd image right now let's see where it goes, it's without dns and it's a fresh install
![20230812_094331](https://github.com/Botspot/wor-flasher/assets/89723867/6713da06-1e68-4b02-aa3f-0b1e6b1bc18d)

**Comment by Botspot** [comment]
I have made a change to wor-flasher that might help. Now, when it displays that error about the image being corrupted, it will display the expected and the actual SHA1 hashes of the file.

**Comment by nasyx-rakeeb** [comment]
> I have made a change to wor-flasher that might help. Now, when it displays that error about the image being corrupted, it will display the expected and the actual SHA1 hashes of the file. This will not solve your problem, but it will help if one of the hashes is missing, for example.

But it won't help, as i stated earlier i modifed the cide to skip the check for hash matching then it throwed another error when it tried to extract the image, it showed `Can't extract the image, image contains invalid data`

**Comment by Botspot** [comment]
I might have just found the problem.

**Comment by nasyx-rakeeb** [comment]
Didn't work on parrot os either.

![16918146944971971806646347273994](https://github.com/Botspot/wor-flasher/assets/89723867/f7797d09-03b7-41f5-829c-29c80ffb25b1)

**Comment by nasyx-rakeeb** [comment]
> I might have just found the problem.

Really, and what's that

**Comment by Botspot** [comment]
My theory is that your first download attempt did fail or was corrupted, but from that point on, aria2c (the downloader program) continued to try to use that corrupted ESD image. The change I just made forces aria2c to restart the download. Try running wor-flasher again and see if it helps.

**Comment by nasyx-rakeeb** [comment]
sure, i will delete the wor flashed and install it from git repository,

**Comment by Botspot** [comment]
wor-flasher should be able to detect the new version and reinstall itself automatically.

**Comment by nasyx-rakeeb** [comment]
I just pulled it manually

**Comment by nasyx-rakeeb** [comment]
Do i need to re download the esd image or should i use the existing one which i download few minutes ago on parrot os

**Comment by nasyx-rakeeb** [comment]
Ok it started re downloading the image even though i had the existing one already in wor-flasher-files

**Comment by nasyx-rakeeb** [comment]
It's downloading esd image, i will update you here, and also i am getting this warning in terminal:

`./install-wor-gui.sh: line 329: bc: command not found`

will it cause any issues or is it occurring due to missing dependency/package

**Comment by Botspot** [comment]
I've now made wor-flasher make sure bc is installed. I was under the impression that it was always preinstalled on all systems, but I guess not. It's used in only one place, and that's to display your available RAM in a human-readible way. Wor-flasher will work without bc installed.

**Comment by nasyx-rakeeb** [comment]
Ah ok, thanks

**Comment by Botspot** [comment]
The fact that wor-flasher is re-downloading the ESD image is a good sign. Has it completed for you yet?

**Comment by nasyx-rakeeb** [comment]
no, not yet, my internet speed is currently 5 mbps. 2gb downloaded

**Comment by Botspot** [comment]
Well I need to go to bed now. Hopefully by my morning, it's solved for you.

**Comment by nasyx-rakeeb** [comment]
> Well I need to go to bed now. Hopefully by my morning, it's solved for you.

Hope so. It is currently morning here 💦 11:00 AM, good night

**Comment by nasyx-rakeeb** [comment]
It worked, thanks for the fix

**Comment by nasyx-rakeeb** [comment]
Fixed
