### ISSUE TITLE
Successfully downloaded ESD image, but it appears to be corrupted. Please run this script again.

### ISSUE THREAD

**Issue by Chrislampwastaken** [Botspot/wor-flasher#137]
Successfully downloaded ESD image, but it appears to be corrupted. Please run this script again.
(Expected SHA1 hash is 5d429a7fb2cd9d3dad4636a2b09d3c8d587f69dd, but downloaded file has SHA1 hash 872312ea981ea55b7d639df6d3aa711adc45295c)

I've ran the script 5 times. It keeps saying that no matter if I choose win10 or win11

I've wasted 5 hours of my day just waiting for this to be done since each time it had to redownload it and I can't waste anymore.

**Comment by Botspot** [comment]
Thanks for reaching out.
This is very important. Can you take note of the "downloaded SHA1 hash" for each run? If that hash was the SAME every 5 times, then something is clearly wrong. But if you ran wor-flasher and it failed with a different "downloaded SHA1 hash", then it indicates your internet connection is so bad that it cannot reliably download a large multi-gigabyte file without corrupting it.
