### ISSUE TITLE
Can’t boot after the windows 11 flashed on the EMMC version of RPI4

### ISSUE THREAD

**Issue by maowenniao** [Botspot/wor-flasher#144]
## Setup:

![74109268da213db97276b1c77649e77e](https://github.com/Botspot/wor-flasher/assets/28671730/6dd449f2-ec1f-4af2-af0c-385279fcd8c0)
![IMG_3097](https://github.com/Botspot/wor-flasher/assets/28671730/5bb98e34-20f0-4336-adb2-261582528628)

- Which version of Windows you chose
-Win11
- Raspberry Pi model
- RPI 4B with emmc (128G) instead of SD Card
- Name of SD card you tried to flash (some are too slow or too small)
- EMMC Samsung brand 
- What day you first downloaded wor-flasher
- Feb, 01,  2024
- What Linux operating system are you using to run wor-flasher on? (Raspberry Pi OS, Twister OS, Debian, etc.)
RASPBERRY PI OS bookworm
## Procedure:
Ok, it is complex，I updated my RPi 4B with an EMMC chip, and I removed my SD card then welding an Samsung EMMC 128G chip instead of the SD card. I flashed a Rpi OS on the emmc, it works well in the last year. And now I try to flash a windows on it.  
I follow the instructions step by step, use a USB stick root an RPI OS, download the Pi-apps and install the WOR software, flash a new version Windows 11 in yo the emmc. Remove the USB stick, power the RPI4 B. Then Raspberry Pi Logo shows, and then it stopped and can not boot from the emmC. I tried my time, it always this.

**Comment by Botspot** [comment]
Somehow I never remember seeing this issue before.
The driver for the EMMC chip likely is not available for WoR, and there is nothing I can do.
