### ISSUE TITLE
PE-based installer integrity chek failed

### ISSUE THREAD

**Issue by Donald-aic** [Botspot/wor-flasher#145]
## Setup:

- I choosed windows 11
-4
- 32GB
- 8.2.24
- "11"(bullseye

## Procedure:
I treid to download Windows for my pi 4 but then the error came and it said exsiting now.

**Comment by Botspot** [comment]
Fixed now in this change: https://github.com/Botspot/wor-flasher/commit/98fe612bb07fd38dbb62a82d6909a59e6d4a2ec9
