### ISSUE TITLE
Wor-Flasher me instala correctamente Windows pero luego no me sale en la Raspberry PI

### ISSUE THREAD

**Issue by LidMai** [Botspot/wor-flasher#156]
## Setup:

- Which version of Windows you chose (Intenté instalar Windows 10)
- Raspberry Pi model (Pi 3 model B)
- Name of SD card you tried to flash (some are too slow or too small) (32Gb V10) 
- What day you first downloaded wor-flasher (27/5/2024)
- What linux operating system you are using to run wor-flasher on. (Raspberry Pi OS, Twister OS, Debian, etc) (RASPBERRY PI OS) 

## Procedure:
Tell us what you did, step by step. Be specific enough so that one of us would be able to replicate your setup.

Al terminar la instalación me da todo correcto, me sale el cartel indicando lo que debo hacer, al colocar la SD dónde tengo el archivo ISO de Windows, la pantalla se me queda en negro, no me sale la imagen de la frambuesa indicando que está cargando, solo se queda la pantalla en negro, y la raspberry no prende el bombillo amarillo, cosa que hace cuando está trabajando, me pueden decir que pasa?

**Comment by TheJosemi98** [comment]
Hola!

Me pasaba exactamente lo mismo con una Fpi4 y encontré este otro hilo que me solucionó el problema ([https://github.com/Botspot/wor-flasher/issues/112]). Básicamente he tenido que generar la imagen a partir del flasher que existe para Windows. Con el flasher de linux me resulta imposible
