### ISSUE TITLE
Translation in french

### ISSUE THREAD

**Issue by Rayman0710** [Botspot/wor-flasher#2]
(I don't really know where I can post that)
Hi, I'm a french guy and I saw what you've made to install windows on raspberry pi, it's pretty cool, and I had modify your install-wor-gui.sh for it be easily to understand for french people, tell me if you want the .sh modified file, it will be an honor for me to give you my translation
Rayman0710

**Comment by Botspot** [comment]
> (I don't really know where I can post that)
> Hi, I'm a french guy and I saw what you've made to install windows on raspberry pi, it's pretty cool, and I had modify your install-wor-gui.sh for it be easily to understand for french people, tell me if you want the .sh modified file, it will be an honor for me to give you my translation
> Rayman0710

Sure, go ahead and upload the file to this issue page.
When I get some spare time, I can try to figure out how hard adding multiple translations to one `bash` script will be.
