### ISSUE TITLE
Failed to mount Error

### ISSUE THREAD

**Issue by LTstrange** [Botspot/wor-flasher#20]
Hi, I try the wor-flasher in rpi 4b 32bit OS. I flash the win11 OS on a 7.7GB USB drive. But I meet an Error that said "Failed to mount /dev/sda2 to /media/pi/WOR-installer/winpart". Thanks for help.
![IMG_20210905_110919](https://user-images.githubusercontent.com/33590343/132113583-ff4655d4-0d63-4014-8f13-87bfdd329270.jpg)

**Comment by Itai-Nelken** [comment]
7gb is too small. A minimum of 32gb is recommended.

**Comment by LTstrange** [comment]
Thank you very much.

> 7gb is too small. A minimum of 32gb is recommended.

 by the way, is that possible to only use the sdcard that rpOS running on, and flash win11 on it self?

**Comment by Itai-Nelken** [comment]
>  by the way, is that possible to only use the sdcard that rpOS running on, and flash win11 on it self? 

No
