### ISSUE TITLE
Do you have a windows version of the Wor Flasher?

### ISSUE THREAD

**Issue by BLEKERS** [Botspot/wor-flasher#21]

**Comment by Botspot** [comment]
Clarification:
There used to be ***only*** a Windows-based installer. Then I made my own tool to imitate the original one.

Go watch nearly any WoR-installation tutorial that was uploaded to Youtube before a week ago. Nearly all of them will explain how to install WoR from a Windows computer. Also, you can read [this tutorial](https://worproject.ml/guides/how-to-install/from-windows) from Please note that I have never used the Windows-based installation tool, and so cannot provide support for it.
