### ISSUE TITLE
Debian SID - Win10 on Pi4

### ISSUE THREAD

**Issue by fiberbus** [Botspot/wor-flasher#25]
I was unable to install using the script as written. Even though the wor-flasher gui completion screen would come up, the pi could not mount the SD card. I had to make some changes. I am not sure if they are all needed. I don't have another SD card to narrow it down. I did have 

I used exfatprogs instead of exfat-utils. Even though I had the latter installed, it would return an error when trying to mount the card
I modified the scripts. Here are the differences. YMMV.

**diff install-wor.sh my_install-wor.sh**
```
191c191
< install_packages 'yad aria2 cabextract wimtools chntpw genisoimage exfat-fuse exfat-utils wget udftools'
---
> install_packages 'yad aria2 cabextract wimtools chntpw genisoimage exfat-fuse exfatprogs wget udftools'
472a473
> sudo mount.exfat-fuse "$(get_partition "$DEVICE" 2)" "$mntpnt"/winpart
474d474
< sudo mount "$(get_partition "$DEVICE" 2)" "$mntpnt"/winpart
478c478
<   sudo mount "$(get_partition "$DEVICE" 2)" "$mntpnt"/winpart || error "Failed to mount $(get_partition` `"$DEVICE" 2) to $mntpnt/winpart"
---
>   sudo mount.exfat-fuse "$(get_partition "$DEVICE" 2)" "$mntpnt"/winpart || error "Failed to mount` `$(get_partition "$DEVICE" 2) to $mntpnt/winpart"
```
**diff install-wor-gui.sh my_install-wor-gui.sh**
```
32c32
< install_packages 'yad aria2 cabextract wimtools chntpw genisoimage exfat-fuse exfat-utils wget'
---
> install_packages 'yad aria2 cabextract wimtools chntpw genisoimage exfat-fuse exfatprogs wget'
```

**Comment by mobilegmYT** [comment]
Currently the tool is meant for RPi OS which is on Buster, I think it might be updated to exfatprogs after RPi OS goes into bullseye too.

**Comment by fiberbus** [comment]
Thank you. I posted it mainly for those who might be stuck and not know how to proceed. Best wishes.

**Comment by Botspot** [comment]
This was fixed recently. Details in issue https://github.com/Botspot/wor-flasher/issues/76
