### ISSUE TITLE
Suggestion: change DL_DIR variable in graphical dialog

### ISSUE THREAD

**Issue by cycool29** [Botspot/wor-flasher#29]
Should have DL_DIR variable added in GUI.

**Comment by Botspot** [comment]
The gui version of the script will obey the DL_DIR variable. Is that what you mean, or are you asking for a graphical way to change the DL_DIR variable?

**Comment by ITdairy** [comment]
> or are you asking for a graphical way to change the DL_DIR variable?

Ya, there should be a dialog to change the DL_DIR variable (maybe DRY_RUN variable also) in graphical way. 😁

**Comment by Botspot** [comment]
Commit https://github.com/Botspot/wor-flasher/commit/629b093ec5f1fe8d4bb391bcb33d42a4472cbfd1 now allows you to change DL_DIR (referred to as "Working directory), in a graphical manner.
