### ISSUE TITLE
Error: Could not detect network connection. 

### ISSUE THREAD

**Issue by cycool29** [Botspot/wor-flasher#30]
I don't know if this is wor-flasher problem or the UEFI. 
When I boot the sd card, it shows 
![Error: Could not detect network connection](https://user-images.githubusercontent.com/88134003/132463770-bf92e5ca-8941-4f6a-9508-158127ca2163.png)
Any fix?

**Comment by shubhamkastwar1** [comment]
Facing same issue "pxe over ipv"
I know i need to disable boot from network and disable secure boot but not able to find it in bios.

Also i am testing it with sd card and in bios it is showing emmc..
Any idea how to fix

**Comment by linus-oof-tips** [comment]
I had that to I reinstalled

**Comment by Botspot** [comment]
This problem is caused by your Pi4 still using an outdated version of the bootloader EEPROM.

To fix it, WoR-flasher now uses an older version of UEFI to accommodated outdated Pies.
To apply the fix:

- Make sure wor-flasher is up to date,
- Then delete this folder so that the older version of UEFI is downloaded: `~/wor-flasher-files/uefipackage`
- Flash the drive again. No need to re-generate the image.

**Comment by shubhamkastwar1** [comment]
Now i am getting this error 
![Uploading 16311089098841434763094683699142.jpg…]()

**Comment by shubhamkastwar1** [comment]
![20210908_191746](https://user-images.githubusercontent.com/85588170/132604047-def2a48d-8f20-496a-841e-0fb7febfe00f.jpg)

**Comment by Botspot** [comment]
I accidentally forgot to change a set of single-quotes to double-quotes in the URL. Sorry about that. It was [fixed](url) within minutes, and so should work fine now.

**Comment by shubhamkastwar1** [comment]
I am trying now, Let's hope it work's. :)

**Comment by shubhamkastwar1** [comment]
![20210909_093233](https://user-images.githubusercontent.com/85588170/132620584-ed8819de-4d1f-4ab5-b85e-ddb1179000d8.jpg)
I think this is working now

**Comment by shubhamkastwar1** [comment]
@Botspot thanks for the help :)

**Comment by Botspot** [comment]
> @Botspot thanks for the help :)

No problem! It's good to know this is now working for you.

**Comment by vk474** [comment]
Do not west your time friends because that  pettern I have done for time
and results came same  show it wile not work 😌

**Comment by Botspot** [comment]
> Do not west your time friends because that pettern I have done for time and results came same show it wile not work 😌

@vk474, if you are still having an issue with WoR-flasher, please [open a new issue](https://github.com/Botspot/wor-flasher/issues/new/choose).

**Comment by cycool29** [comment]
Thanksss now it worked and i installed windows 11 on rpi successfully!
![1631181146984-1717571739](https://user-images.githubusercontent.com/88134003/132664602-df7cfc6f-8268-4d23-9abe-7261c31933cd.jpg)

**Comment by Alfpv** [comment]
Hey, I am getting the same 2 'could not detect network connection' errors, but none of the others, is that ok? Or should I be worrying?

**Comment by Botspot** [comment]
> Hey, I am getting the same 2 'could not detect network connection' errors, but none of the others, is that ok? Or should I be worrying?

That is fine.

**Comment by Subhojit131** [comment]
> > Hey, I am getting the same 2 'could not detect network connection' errors, but none of the others, is that ok? Or should I be worrying?
> 
> That is fine.

I am also getting the 2 could not detect network connection errors and its not getting past that screen I have waited for 30 minutes and more still its stuck

**Comment by not-real-alex** [comment]
This issue will solve itself with time. if not 

this is caused by a slow boot drive "SD card or USB Drive"
you could have this same issue wired to the internet or not connected at all.
Sometimes reinstalling the operating system to the drive helps.

**Comment by Subhojit131** [comment]
> This issue will solve itself with time. if not 
> 
> this is caused by a slow boot drive "SD card or USB Drive"
> you could have this same issue wired to the internet or not connected at all.
> Sometimes reinstalling the operating system to the drive helps.  

I also thought that this could be possible thats why I tried changing the drive but even after changing it is stuck in that same screen could it be related to the EPROM? I will try to update it and try again today
