### ISSUE TITLE
Couldn't find installation disk

### ISSUE THREAD

**Issue by AndryX19** [Botspot/wor-flasher#34]
I repeat the process with wor-flasher from raspbian, also with the updated uefi firmware (1.3.1), same error..
![20210910_143147](https://user-images.githubusercontent.com/66414150/132934892-3bc0dedd-efc9-46bf-a19e-7f83f47689fb.jpg)
![20210910_143032](https://user-images.githubusercontent.com/66414150/132934895-bac3ea63-7ae6-47ba-8fde-21fc8223f3f0.jpg)
![20210910_143020](https://user-images.githubusercontent.com/66414150/132934896-ceeebe62-da8d-4943-8e4d-5dd19d1c40e0.jpg)

**Comment by Botspot** [comment]
Try updating the EEPROM on the Pi4.

From Raspberry Pi OS:
```
sudo rpi-eeprom-update -a
```

**Comment by AndryX19** [comment]
it's just the latest

**Comment by Botspot** [comment]
> it's just the latest

@AndryX19 What do the logs look like?

**Comment by AndryX19** [comment]
forgive the wait, I had exams at the university, tomorrow I send the logs , I hope we can solve it

**Comment by AndryX19** [comment]
@Botspot where are locate the log files?

**Comment by Botspot** [comment]
> @Botspot where are locate the log files?

You need to click the "Logs" button. If you didn't, then try booting the pi again and hoping the same error occurs.

**Comment by AndryX19** [comment]
I can't use mouse and keyboard after boot and I can't click on logs button...

**Comment by AndryX19** [comment]
@Botspot I have news. Investigating I discovered that the problem lies in the bootloader and its inability to read sectors of 4096 compared to the classic 512. Since the external sata-usb supports emulate the passage from 4096bit to 512bit and therefore extend the compatibility to old systems and limitations, as in this case. So I'll try another older sata-usb adapter and hope it works, because with other systems it works but with win doesn't

**Comment by christopherdev** [comment]
@AndryX19 I have the same issue, I used an old enclosure and a new sata adapter and both shows the same error and can't view logs. What sata adapter that is recommended for this to work?

**Comment by MuffinGod1** [comment]
I also have the same issue. Couldn't read install disk, keyboard and mouse unresponsive. Trying to install in an argon 1 m.2 enclosure.

**Comment by AndryX19** [comment]
I'm waiting for deskpi pro v2, same but also for 2.5" sata disk (in my case ssd) and m.2 disk

**Comment by zShqdows** [comment]
Should this be closed due to inactivity @Botspot ?
