### ISSUE TITLE
Blank screen but drive light going on and off

### ISSUE THREAD

**Issue by TheTown777** [Botspot/wor-flasher#37]
Ive been waiting 2 hours and im using a rpi4 12 gig card trying to install windows 11 but nothing is showing on the screen

**Comment by TheTown777** [comment]
oh im also using twister os

**Comment by TheTown777** [comment]
This is what the bootloader says before it goes blank![image](https://user-images.githubusercontent.com/86498432/133129317-c4948c5c-5c45-46aa-9f4a-c2c9333c987a.jpeg)

**Comment by TheTown777** [comment]
You can close this issue i figured it out

**Comment by Botspot** [comment]
> You can close this issue i figured it out

What did you do to make it work?

**Comment by TheTown777** [comment]
use a usb hdd
