### ISSUE TITLE
uup_download_linux.sh failed, most likely due to unreliable Internet

### ISSUE THREAD

**Issue by r2d2agr** [Botspot/wor-flasher#42]
pi4 2gb
microSD HC V30 sandisk extreme U3 A1 32Gb
Raspbian OS latest

normal procedure, select win11, Pi4/400, next, en/us, next, microSD, next, flash!
the process failed 4 times, with this message:
```
Exporting Windows 10 Professional to install.wim...
[ERROR] "/Windows/System32/CatRoot/{F750E6C3-38EE-11D1-85E5-00C04FC295EE}/Microsoft-Windows-Enterprise-Desktop-Shared-Removable-Package31bf3856ad364e35arm64~~10.0.22458.1000.cat": blob not found
SHA-1 message digest of missing blob:
2463db131bcacb290589f826f687d4e29b7bc02a
ERROR: If this is a delta WIM, use the --ref argument to specify the WIM(s) on which it is based.
ERROR: Exiting with error code 55:
A file resource needed to complete the operation was missing from the WIM.
Failed to export Windows 10 Professional to install.wim

uup_download_linux.sh failed, most likely due to unreliable Internet.
Trying again in 1 minute. (Attempt 1 of 4)
```
image with the 4th attempt!
![pi_error2](https://user-images.githubusercontent.com/46817124/134267239-1a636706-181c-4946-b953-8dfa1d46eeb6.PNG)

**Comment by Botspot** [comment]
Looks like your issue and #41 are the same problem.
To keep things simple, I'm closing this issue and we can troubleshoot on the other one.

Thank you for your understanding. :)
