### ISSUE TITLE
[error] File：xxx\rtscom.dll（121）

### ISSUE THREAD

**Issue by ylsislove** [Botspot/wor-flasher#49]
I encountered this error(as shown below) installing windows11 on raspberry pie 4. It is stuck here. I don't know how this error occurs and how to solve it.

![IMG_20211012_011348](https://user-images.githubusercontent.com/41816449/136830002-10c6d336-9d5e-4b91-a024-081ec8ccb59f.jpg)

Can anyone help me? Should I restart my device?

**Comment by Botspot** [comment]
This appears to be an error occurring in the Preinstallation Environment. I've asked the developer for insight for this error. We'll see what he says.
