### ISSUE TITLE
Error message: "User exited when chosing windows version and RPi model´

### ISSUE THREAD

**Issue by jayjupdhig** [Botspot/wor-flasher#50]
Hi

I've done that steps here:
https://www.tomshardware.com/how-to/install-windows-11-raspberry-pi

Then i get the message ´Error message: "User exited when chosing windows version and RPi model´...

Why that?

And why i have to wait for 60 seconds - just to have the time to cancel it while that 60 seconds after entering "y" for "Yes"... really really strange i.m.o.

Screenshot here:
![123](https://user-images.githubusercontent.com/42765391/137300857-5eb397da-3ff9-430c-b909-ee10bea50186.JPG)

Thank you very much for your feedback. :-) 

With kind regards,
Jan

**Comment by jayjupdhig** [comment]
On my VirtualBox VM... (i also pressed Enter key after entering "y"... )
![333](https://user-images.githubusercontent.com/42765391/137304579-eb80f636-cce0-4b95-8418-a2532eb2888e.JPG)

**Comment by kosuodhmwa** [comment]
Thank you very much!! :-)

**Comment by Botspot** [comment]
I've made a change to the `echo_white` function to set the text's background to black.

**Comment by jayjupdhig** [comment]
Thank you very much; will look on it tomorrow on working.

Best regards, Jan

**Comment by jayjupdhig** [comment]
And; What do you mean with that?
-> ´In the zip file you extracted earlier find instructions.txt and open it.´

Which .zip file i earlier extracted?

**Comment by jayjupdhig** [comment]
@cycool29 : Now i saw it, i need to click the symbol above.. not to enter it...

**Comment by cycool29** [comment]
> Now i created a discord account and tried to join your channel on https://discord.com/invite/jQCpfVK ...
>
> But then i need to send a ´✅´ but i can't enter anything on your channel:

Well that's not **my channel**, I am not dev of WoR project.

**Comment by jayjupdhig** [comment]
@cycool29 : Oh, OK, thank you for your feedback...

I can't find that file ´instructions.txt´ on your discord server - no where, neither on "tutorials", not on "downloads" channel... 

Maybe somebody has that file?

**Comment by cycool29** [comment]
> @cycool29 : Oh, OK, thank you for your feedback...
> 
> I can't find that file ´instructions.txt´ on your discord server - no where, neither on "tutorials", not on "downloads" channel...
> 
> Maybe somebody has that file?

In the tutorial, it says:
> Download the latest .zip file in 📁downloads and extract it


The zip file it means is this:

![image](https://user-images.githubusercontent.com/88134003/137461002-55df88f3-5919-450d-aa7e-f0a1c7317019.png)

You will need it for optimizing the wim file, as well as the `Instructions.txt` is in it. 

I recommend you to watch [the youtube tutorial](https://www.youtube.com/watch?v=WCW4KljdHhM) for more thorough tutorial.

**Comment by jayjupdhig** [comment]
@cycool29 : Thank you very very much!!

But so i saw, the "NTLite Preset"-Link directs to  "WoR" - not "NTLite[.zip]" so something like that...  https://cdn.discordapp.com/attachments/852180184941199422/859455174254526484/WoR_0.3.2.zip

Anyway, nwo i got the ´instructions.txt´ file... :-)

**Comment by cycool29** [comment]
> @cycool29 : Thank you very very much!!
> 
> But so i saw, the "NTLite Preset"-Link directs to "WoR" - not "NTLite[.zip]" so something like that... https://cdn.discordapp.com/attachments/852180184941199422/859455174254526484/WoR_0.3.2.zip
> 
> Anyway, nwo i got the ´instructions.txt´ file... :-)

Ya, as the name suggests: NTLite **Preset**, that's not the NTLite app.

**Comment by jayjupdhig** [comment]
Solved
