### ISSUE TITLE
System License Violation

### ISSUE THREAD

**Issue by sparker0** [Botspot/wor-flasher#55]
## Setup:

- Which version of Windows you chose. Windows 11
- Raspberry Pi model -  4
- Name of SD card you tried to flash (some are too slow or too small) - External USB drive
- What day you first downloaded wor-flasher - 10/28/2021
- What linux operating system you are using to run wor-flasher on. (Raspberry Pi OS, Twister OS, Debian, etc)
Raspberry Pi OS
## Procedure:
Tell us what you did, step by step. Be specific enough so that one of us would be able to replicate your setup.
Followed the instructions at https://www.tomshardware.com/how-to/install-windows-11-raspberry-pi
When the system rebooted the last time, it blue-screened with the error: "System License Violation"

**Comment by Botspot** [comment]
I've asked a WoR developer for insight into this issue.

**Comment by Botspot** [comment]
He says:

> probably corrupted/missing key in the registry
they could try to re-install
and maybe download the image again / or another version

**Comment by sparker0** [comment]
I retried the install and it completed. Now I need to figure out why none of my wireless networks are showing up.

**Comment by cycool29** [comment]
> I retried the install and it completed. Now I need to figure out why none of my wireless networks are showing up.

Refer to [this](https://github.com/Botspot/wor-flasher/issues/54#issuecomment-953390630).

**Comment by Botspot** [comment]
Good to know it's working for you.
As of yet, the WiFi drivers have not been written yet. You will have to use Ethernet.
