### ISSUE TITLE
Failed to Copy  boot.wim to bootpart/sources

### ISSUE THREAD

**Issue by theroyalseeker12** [Botspot/wor-flasher#58]
## Setup:
I have rpi4 2 GB version 
Sdcard is 32 GB strontium class 10 

## Procedure:
Everytime I am getting an error 
An error has occurred:
Failed to Copy /home/pi/wor-flasher-files/isomount/sources/boot wim to /media/pi/WOR-installer/bootpart/sources

Also at the starting of script 
 Seeing a message 
Lsblk:none: not a block device

**Comment by JeromTWinL** [comment]
It looks like you're usb drive has been loosed while it's running.
