### ISSUE TITLE
Not booting

### ISSUE THREAD

**Issue by catdogmat** [Botspot/wor-flasher#67]
## Setup:

- Which version of Windows you chose
- 11
- Raspberry Pi model
- 3B+
- Name of SD card you tried to flash (some are too slow or too small)
- 32gb A1 rated card
- What day you first downloaded wor-flasher
- 18/01/2022
- What linux operating system you are using to run wor-flasher on. (Raspberry Pi OS, Twister OS, Debian, etc)
- Raspberry Pi OS

## Procedure:
Tell us what you did, step by step. Be specific enough so that one of us would be able to replicate your setup.
Use wor flasher to flash wor to my sd card
Put the card into the raspberry pi
See a no signal screen

**Comment by Botspot** [comment]
We've been having problems with Pi3 compatibility. Some people say Pi3s work, while others say they don't.

Even if you did get Windows running on your Pi3, it would be mostly unusable. (Windows is not designed with 1GB of RAM in mind)
I would suggest getting a Pi4, but right now that's nearly impossible. My advice to you is to stick with Linux.
