### ISSUE TITLE
Dual Boot

### ISSUE THREAD

**Issue by Maki2007** [Botspot/wor-flasher#68]
Hello
I have a great OS with pinn os, that include pi os, android and some other os on my ssd disk. I dont want to clear my disk. I there a way, I can add windows, without wipe my other OS??

**Comment by Botspot** [comment]
Windows's partition structure is fairly concrete and unchangeable.
There's a good [discussion](https://github.com/procount/pinn/issues/481) on the PINN repository about the various ways to dual-boot WoR and another operating system using PINN. The general consensus was that it's impossible, unless you have a spare USB drive and know programming.

The best way to avoid clearing your disk is to get another one. I recommend the SanDisk Extreme line of microsd cards - they are fast, cheap, and seem harder to corrupt compared to other brands.
