### ISSUE TITLE
wor-flasher error during installation

### ISSUE THREAD

**Issue by bobster316** [Botspot/wor-flasher#7]
I am getting the following error when running the installation 

An error has occurred 
Failed to generation a Windows ISO!
(uup_download_linux.sh script indicated a failure)
Exiting now

**Comment by Botspot** [comment]
Either your Internet connection is unreliable, or you ran out of available disk space.

I will soon upload these changes:

- The uupdump script will retry 4 times before giving up.
- If you have insufficient disk space, an error will occur.

**Comment by lobotech13** [comment]
I have the same problem with uup_download_linux.sh...
Impossible to generate the ISO.
Is it possible to generate the ISO manually ?

**Comment by Botspot** [comment]
> I have the same problem with uup_download_linux.sh... Impossible to generate the ISO. Is it possible to generate the ISO manually ?

Sometimes the uupdump website is unstable. Usually you can solve this by specifying an older Windows Update ID.
