### ISSUE TITLE
Unable to complete copying files from image to device

### ISSUE THREAD

**Issue by 3DPi2** [Botspot/wor-flasher#71]
## Setup:

- Which version of Windows you chose - 11
- Raspberry Pi model - 3b+ transferring data to 4b SDD
- Name of SD card you tried to flash (some are too slow or too small) Samsung 970 EVO Plus Series - 250GB PCIe NVMe - M.2 Internal SSD (MZ-V7S250B/AM)
- What day you first downloaded wor-flasher - 3/18/22
- What linux operating system you are using to run wor-flasher on. (Raspberry Pi OS, Twister OS, Debian, etc) - Raspberry Pi OS

## Procedure:
Tell us what you did, step by step. Be specific enough so that one of us would be able to replicate your setup.

Using a Raspberry pi 3b+ to download WoR Flasher to transfer over to the 4b SDD:

- Downloaded WoR-Flasher
- Ran setup for Windows 11 installs, en-us language
- Selected on device attached via USB, Samsung 970 EVO Plus Series - 250GB PCIe NVMe - M.2 Internal SSD (MZ-V7S250B/AM)

All files are able to download just fine and the program is able to generate a complete Windows image just fine.  Partitions are able to be generated just fine as well.  

After it mounts the image and started the process "Copying files from image to device" this is as far as it gets:

-Boot files
-EPi files
-boot .wlm
-install.wim

After that it gets hung  over an hour with no progress.

Stumped on what to do at this point.

**Comment by Botspot** [comment]
It appears you have encountered the elusive install.wim copying error. Several people have reported it, and there are no solutions other than to use a different/faster storage drive.

The source of the problem is beyond my realm to fix, because this occurs during the PE-based installer step, which is developed by the WoR team, not by me.
