### ISSUE TITLE
cant download OS.

### ISSUE THREAD

**Issue by Visseb** [Botspot/wor-flasher#74]
im getting this error, running Wor installer App.

An error has occurred:
Failed to determine a hashsum for WoR PE-based installer.
URL: http://worproject.ml/dldserv/worpe/gethashlatest.php
Exiting now.

**Comment by Botspot** [comment]
Update: I went to the WoR discord server and the maintainer for worproject.ml shared these two screenshots:
![unknown](https://user-images.githubusercontent.com/54716352/167179322-54acd513-739d-4225-9e59-bb56995aaca9.png)
![unknown (1)](https://user-images.githubusercontent.com/54716352/167179327-d53aec1a-10d6-4747-986b-83b122221ef2.png)
It would appear that someone under the impression that WoR is illegal reported the website and had it taken down. This is eerily similar to the takedown of youtube-dl last year.

If I wasn't busy right now, I would try to edit WoR-Flasher to avoid depending on worproject.ml for anything.

**Comment by Visseb** [comment]
Okey, take your time, im glad if you can help 😄

**Comment by Botspot** [comment]
The website maintainer has moved the website to a new domain: https://worproject.com
I've updated the scripts to reflect this. Try WoR-Flasher again. It should work now.
