### ISSUE TITLE
Package 'exfat-utils' has no installation candidate

### ISSUE THREAD

**Issue by Gozzeh** [Botspot/wor-flasher#76]
I'm running ubuntu 22.04 anmd it looks like the exfat-utils package is no longer available.

Is there an easy work around for this?

**Comment by Itai-Nelken** [comment]
In Ubuntu 22.04 `exfat-utils` is replaced with `exfatprogs`.
See https://askubuntu.com/questions/1403900/how-to-install-exfat-utils-and-hddtemp-on-ubuntu-22-04

**Comment by Gozzeh** [comment]
but what do i need to change to get it to use that and stop using
exfat-utils ...?

**Comment by Itai-Nelken** [comment]
Replace exfat-utils with exfatprogs in line 239 of install-wor.sh: 
https://github.com/Botspot/wor-flasher/blob/main/install-wor.sh#L239

That should fix it.

**Comment by Gozzeh** [comment]
Thanks!

I ended up just removing the exfat-utils and i got it to work but your
method seems far more sensible!

**Comment by Itai-Nelken** [comment]
@Botspot a check should be added to install exfatprogs on ubuntu 22.04.

**Comment by Botspot** [comment]
> @Botspot a check should be added to install exfatprogs on ubuntu 22.04.

I was under the impression that exfatprogs had to be used differently and it would involve additional changes to the script. Since I don't use Ubuntu, I had no way to know if it worked.
But if exfatprogs is a drop-in replacement for exfat-utils, that would be great!

**Comment by Botspot** [comment]
I've pushed a proper fix to the script.
