### ISSUE TITLE
file cant download

### ISSUE THREAD

**Issue by rummboysrc** [Botspot/wor-flasher#78]
trying to download then i get this.

uup_download_linux.sh failed, most likely due to unreliable Internet.
Trying again in 1 minute. (Attempt 1 of 4)

**Comment by Botspot** [comment]
The error "`uup_download_linux.sh failed, most likely due to unreliable Internet.`" just **summarizes** the problem.
By itself, it doesn't help us find the problem. Please share the terminal output **before** that error.

**Comment by Botspot** [comment]
> It's likely EMPTY_FILELIST, I'm encountering it now...

Check if uupdump.net is blocked by your firewall.
