### ISSUE TITLE
Failed to generate ISO

### ISSUE THREAD

**Issue by petragom** [Botspot/wor-flasher#8]
![F26D35F3-C8A0-4AA1-9654-87DF655F579B](https://user-images.githubusercontent.com/64976652/131868837-f941f515-d61a-4d67-9a72-6adfb58adbc9.jpeg)

I’m trying to install but I get this error.

I’ve used a clean install of Raspberry OS 32 bit on a 16gb card and selected an external SSD of 256Gb to install it on.

(Thank you so much for making this!!! I’ve wanted to try WOR for so long, but couldn’t because the previous way requires a Windows installation)

**Comment by Itai-Nelken** [comment]
You ran out if space. The windows iso is over 4gb so you need at least 5gb if free space.

**Comment by pranavr2003** [comment]
@petragom It's either that you ran out of space, or it was a web server issue. For me, it was a web server issue, so it worked like a charm when I tried again

**Comment by Botspot** [comment]
> @petragom It's either that you ran out of space, or it was a web server issue. For me, it was a web server issue, so it worked like a charm when I tried again

The error in this person's screenshot says "No space left on device", so it's definitely a storage space issue.

**Comment by pranavr2003** [comment]
@Botspot Gosh I didn't see that, gotta watch it

**Comment by Botspot** [comment]
If an image is being generated AND the free disk space is less than 7GB (the total size of uupdump folder after a flash), an error will occur saying:
```
Your system does not have enough usable disk space to generate a Windows image.
Please free up space or set the DL_DIR variable to a drive with more capacity.
7GB is necessary.
```
