### ISSUE TITLE
Wifi not showing 

### ISSUE THREAD

**Issue by Zbrooklyn** [Botspot/wor-flasher#80]
I'm using a raspberry pi 4. I installed windows using the flasher and did not modify configuration file.

The only network option it ethernet even though raspberrypi 4 has wifi and Bluetooth. Do I need a special driver?

**Comment by Botspot** [comment]
WiFi driver is unavailable. Please read [the Useful information heading](https://github.com/Botspot/wor-flasher#useful-information) in the readme.

**Comment by Zbrooklyn** [comment]
Will a wifi dongle work?

**Comment by Botspot** [comment]
> Will a wifi dongle work if it comes with drivers? @Botspot

Previously, the answer to this question was "no", but recently someone found a USB Wi-Fi dongle that does have a compatible driver. It had to be compiled, but is now available for anyone to try out.
You would need a specific dongle for this driver to be any good.

Source: https://worproject.com/faq#usb-wi-fi-drivers
