### ISSUE TITLE
Unable to install on Ubintu 22.04 due to deprecated exfat-utils package

### ISSUE THREAD

**Issue by grinux** [Botspot/wor-flasher#87]
Setup sh stops with error.
Details is here:
https://askubuntu.com/questions/1403900/how-to-install-exfat-utils-and-hddtemp-on-ubuntu-22-04

**Comment by Botspot** [comment]
> Setup sh stops with error.

What is the actual error? I am aware that exfat-utils is being replaced by exfatprogs, but the `install-wor.sh` script should work around that.
Here is the code used:
```bash
#install exfat partition manipulation utility. exfatprogs replaces exfat-utils, but they cannot both be installed at once.
if package_available exfatprogs && ! package_installed exfat-utils ;then
  install_packages exfatprogs || exit 1
else
  install_packages exfat-utils || exit 1
fi
```

**Comment by Botspot** [comment]
See: https://github.com/Botspot/wor-flasher/issues/76

**Comment by Botspot** [comment]
This has been fixed in commit https://github.com/Botspot/wor-flasher/commit/b9e099331cdabee003f22da3a9b59ad7924a8e22
