### ISSUE TITLE
Failed to determine a hashsum for WoR PE-based installer.

### ISSUE THREAD

**Issue by Ueba3bala** [Botspot/wor-flasher#88]
## Setup:

- Which version of Windows you chose
- 10
- 
- Raspberry Pi model
- 4 Model B
- 
- Name of SD card you tried to flash (some are too slow or too small)
- 
- What day you first downloaded wor-flasher
- 29.06.2022
- 
- What linux operating system you are using to run wor-flasher on. (Raspberry Pi OS, Twister OS, Debian, etc)
- XUbuntu 20.04 Kernel 5.13.0-51-generic 

## Procedure:
Tell us what you did, step by step. Be specific enough so that one of us would be able to replicate your setup.

I get the following error message: 
```
Input configuration:
DL_DIR: /home/runner/wor-flasher-files
RUN_MODE: gui
RPI_MODEL: 4
DEVICE: /dev/mmcblk0
CAN_INSTALL_ON_SAME_DRIVE: 1
UUID: 26bd69e1-3ed6-4116-b7c8-f5dea4806fe6
WIN_LANG: de-de
CONFIG_TXT: ⤵
  > # don't change anything below this point #
  > arm_64bit=1
  > enable_uart=1
  > uart_2ndstage=1
  > enable_gic=1
  > armstub=RPI_EFI.fd
  > disable_commandline_tags=1
  > disable_overscan=1
  > device_tree_address=0x1f0000
  > device_tree_end=0x200000
  > dtoverlay=miniuart-bt
CONFIG_TXT: ⤴

Downloading WoR PE-based installer from Google Drive
Failed to determine a hashsum for WoR PE-based installer.
URL: http://worproject.com/dldserv/worpe/gethashlatest.php
```

**Comment by Botspot** [comment]
This error basically means that worproject.com was inaccessible from your location. It may have been due to a site outage, but we've also received reports of this site being blocked by some internet firewalls.
Please check that http://worproject.com/dldserv/worpe/gethashlatest.php is accessible from your network, and try again.
