### ISSUE TITLE
Installation disk needs to be recreated in order to try again

### ISSUE THREAD

**Issue by on4xb** [Botspot/wor-flasher#99]
At the preinstall evironment i get an error and the installation fails
Error
Installation disk needs to be recreated in order to try again
Hardware is a raspberry 3b+ with 1 tb usb 3.1 external SSD. At this point the 64GbSDcard has been removed as per instruction.
I assume the the build of the ISO was succesfull

Any pointers/help pse

Bert

**Comment by Botspot** [comment]
First, as a warning, I don't maintain the Preinstallation Environment. So if something goes wrong there, there are few things I can do, other than to show the error to a WoR maintainer, who usually has no idea how to help. :(

Could you take a picture of your screen and attach it to this Github Issue?

**Comment by on4xb** [comment]
raspberry 3b+ with 1 tb usb 3.1 external SSD
![2022-09-24 21 38 05](https://user-images.githubusercontent.com/63606084/192115727-96b57294-715b-4cdd-94ab-808421f29d0e.jpg)
![2022-09-24 21 38 21](https://user-images.githubusercontent.com/63606084/192115731-dc97273e-74ef-4c32-83d4-f862478febbe.jpg)

**Comment by on4xb** [comment]
Hello,
Today (and after a long wait) i received my PI4-8Gb. Itried again to install Windows 11 and went like a charm. I used the same SDcard and SSD. In other words the error happens only with the rpi3B+ version. Tnx for the support anyway

Bert

**Comment by Botspot** [comment]
> After several failed attempts I found out that my micro SD card was the problem. At the time, I was using a Samsung Evo card which never worked and today I found another SD card around the house called Samsung Evo Ultra which worked.
> 
> Most Samsung card's are really good but I bought this messed up one really really super cheap on Amazon. I am thinking it was probably a fake card from a 3rd party seller. The card that worked was bought at best buy

Perhaps Wor-Flasher can be improved to detect cards like yours. Could you insert the defective card into your pi with a usb adapter, then send me the output of `lsusb`?

**Comment by susanbles** [comment]
I have got this problem too, installing windows 10 on rpi4 4Gb. I tried to instal from buster 32 bit on sandisk 64Gb flashdrive and from 64bit bullseye on 32 Gb class10 micro Sd  on sandisk flashdrive  and from buster 64 bit on sandisk 64Gb flashdrive on forementioned micro Sd. All used cards an drives work well with other OS's.

**Comment by Botspot** [comment]
> I have got this problem too, installing windows 10 on rpi4 4Gb. I tried to instal from buster 32 bit on sandisk 64Gb flashdrive and from 64bit bullseye on 32 Gb class10 micro Sd on sandisk flashdrive and from buster 64 bit on sandisk 64Gb flashdrive on forementioned micro Sd. All used cards an drives work well with other OS's.

Flash drives are not recommended and SD cards are hit or miss.
Could you click the "Logs" button and send a picture of the error?

**Comment by susanbles** [comment]
Thanks for your advice, another micro sd card did the trick.
